backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'blog-post' }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Publish Date', widget: 'datetime' }
      - { name: 'description', label: 'Description', widget: 'text' }
      - { name: 'featuredpost', label: 'Featured Post', widget: 'boolean' }
      - { name: 'featuredimage', label: 'Featured Image', widget: image }
      - { name: 'body', label: 'Body', widget: 'markdown' }
      - { name: 'tags', label: 'Tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        name: 'index'
        label: 'Landing Page'
        fields:
          - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'index-page' }
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: subheading, label: Subheading, widget: string }
          - {
              name: mainpitch,
              label: Mainpitch,
              widget: object,
              fields:
                [
                  { name: title, label: Title, widget: string },
                  { name: description, label: Description, widget: text },
                ],
            }
          - { name: description, label: Description, widget: string }
          - {
              name: intro,
              label: Intro,
              widget: object,
              fields:
                [
                  { name: heading, label: Heading, widget: string },
                  { name: description, label: Description, widget: text },
                  {
                    name: blurbs,
                    label: Blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              name: main,
              label: Main,
              widget: object,
              fields:
                [
                  { name: heading, label: Heading, widget: string },
                  { name: description, label: Description, widget: text },
                  {
                    name: image1,
                    label: Image1,
                    widget: object,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: alt, label: Alt, widget: string },
                      ],
                  },
                  {
                    name: image2,
                    label: Image2,
                    widget: object,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: alt, label: Alt, widget: string },
                      ],
                  },
                  {
                    name: image3,
                    label: Image3,
                    widget: object,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: alt, label: Alt, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about/index.md'
        name: 'about'
        label: 'About'
        fields:
          - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'about-page' }
          - { name: 'title', label: 'Title', widget: 'string' }
          - { name: 'body', label: 'Body', widget: 'markdown' }
      - file: 'src/pages/products/index.md'
        name: 'products'
        label: 'Products Page'
        fields:
          - {
              name: 'templateKey',
              label: 'Template Key',
              widget: 'hidden',
              default: 'product-page',
            }
          - { name: title, label: Title, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: description, label: Description, widget: string }
          - {
              name: intro,
              label: Intro,
              widget: object,
              fields:
                [
                  { name: heading, label: Heading, widget: string },
                  { name: description, label: Description, widget: text },
                  {
                    name: blurbs,
                    label: Blurbs,
                    widget: list,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: text, label: Text, widget: text },
                      ],
                  },
                ],
            }
          - {
              name: main,
              label: Main,
              widget: object,
              fields:
                [
                  { name: heading, label: Heading, widget: string },
                  { name: description, label: Description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: alt, label: Alt, widget: string },
                      ],
                  },
                  {
                    name: image2,
                    label: Image2,
                    widget: object,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: alt, label: Alt, widget: string },
                      ],
                  },
                  {
                    name: image3,
                    label: Image3,
                    widget: object,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: alt, label: Alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              name: testimonials,
              label: Testimonials,
              widget: list,
              fields:
                [
                  { name: quote, label: Quote, widget: string },
                  { name: author, label: Author, widget: string },
                ],
            }
          - { name: full_image, label: Full_image, widget: image }
          - {
              name: pricing,
              label: Pricing,
              widget: object,
              fields:
                [
                  { name: heading, label: Heading, widget: string },
                  { name: description, label: Description, widget: string },
                  {
                    name: plans,
                    label: Plans,
                    widget: list,
                    fields:
                      [
                        { name: plan, label: Plan, widget: string },
                        { name: price, label: Price, widget: string },
                        { name: description, label: Description, widget: string },
                        { name: items, label: Items, widget: list },
                      ],
                  },
                ],
            }
